### ISSUE TITLE
Some tabs are looking janky on ultra-wide monitors

### ISSUE THREAD

**Issue by carlosblanc0** [LightningWB/lightspeed.js-site#1]
![Screen Shot 2021-07-11 at 7 28 06 PM](https://user-images.githubusercontent.com/30513653/125212858-26d23880-e27e-11eb-9d1d-52dd1f5dca86.png)
![Screen Shot 2021-07-11 at 7 28 39 PM](https://user-images.githubusercontent.com/30513653/125212865-35205480-e27e-11eb-9807-e689cd2cdb1c.png)

All I'm saying is this could be improved (:

**Comment by LightningWB** [comment]
should now not look as ugly on mobile. would love to see what it looks like now when you get a chance @carlosblanc0.

**Comment by carlosblanc0** [comment]
Cool cool! Would you like me to 'create-react-app' a landing page service? I could use sass to do the styling, ESlinting, and all that good stuff. 

EDIT: typo.

**Comment by LightningWB** [comment]
It would be great to have a better home page, but you don't have to go out of your way to make it. Please make a pr if you end up deciding to make it. :)
